#!/usr/bin/env bash
# This script transfers a file to a remote server using scp with disabled strict host key checking

# Check if the number of arguments is less than 4
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign arguments to variables
FILE="$1"
IP="$2"
USER="$3"
KEY="$4"

# Transfer the file
scp -i "$KEY" -o StrictHostKeyChecking=no "$FILE" "$USER@$IP:~/"
