#!/usr/bin/env bash
# Installs Nginx and configures it to redirect /redirect_me to YouTube

# Install nginx
apt-get update
apt-get install -y nginx

# Create custom configuration with redirection
cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF

# Restart Nginx using service (not systemctl)
service nginx restart
